# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kejcaK-DdV5fmhWW3W9tRZpQ3i3isMao
"""

import pandas as pd
from google.colab import files

# Upload and load CSV file into DataFrame
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])

# Clean and preprocess the data
df['DATE'] = pd.to_datetime(df['DATE'], errors='coerce')
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Summarize by importer, export country, and origin country
top_importers = df.groupby('importer_name')['total_value_usd'].sum().nlargest(10)
top_export_countries = df.groupby('export_country')['total_value_usd'].sum().nlargest(10)
top_origin_countries = df.groupby('origin_country')['total_value_usd'].sum().nlargest(10)

# Summarize by products
top_products_by_hs_code = df.groupby('hs_code')['total_value_usd'].sum().nlargest(10)
top_products_by_description = df.groupby('product_description')['total_value_usd'].sum().nlargest(10)

# Summarize trade trends over time
trade_trends = df.groupby('date')['total_value_usd'].sum()

# Output summaries
print("Top Importers:\n", top_importers)
print("Top Export Countries:\n", top_export_countries)
print("Top Origin Countries:\n", top_origin_countries)
print("Top Products by HS Code:\n", top_products_by_hs_code)
print("Top Products by Description:\n", top_products_by_description)
print("Trade Trends Over Time:\n", trade_trends)

# Save and download the updated CSV
df.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')